import type { CrmFallbackNavigation } from '../types/global';

export const fallbackNavigation: CrmFallbackNavigation = {
  modules: [
    { name: 'Tableau de bord', slug: 'dashboard', routePath: '/', active: true, sortOrder: 0 },
    {
      name: 'Réservations véhicules',
      slug: 'reservations',
      routePath: '/reservations',
      active: true,
      sortOrder: 10,
      menuBadge: 'Martin',
      menuBadgeColor: '#95002e',
      showMenuBadge: true,
    },
    {
      name: 'Location matériel',
      slug: 'locations-materiel',
      routePath: '/locations-materiel',
      active: true,
      sortOrder: 15,
    },
    { name: 'Équipe', slug: 'equipes', routePath: '/equipes', active: true, sortOrder: 16 },
    { name: 'Congés & Absences', slug: 'conges', routePath: '/conges', active: true, sortOrder: 17 },
    {
      name: 'Pilotage commercial',
      slug: 'pilotage-commercial',
      routePath: '/pilotage-commercial',
      active: true,
      sortOrder: 19,
    },
    {
      name: 'Rapport de visite',
      slug: 'tournees-representants',
      routePath: '/rapport-visite',
      active: true,
      sortOrder: 18,
    },
    { name: 'Promo', slug: 'documents-promo', routePath: '/documents/promo', active: true, sortOrder: 241 },
    {
      name: 'Fiches techniques',
      slug: 'documents-fiches-techniques',
      routePath: '/documents/fiches-techniques',
      active: true,
      sortOrder: 242,
    },
    {
      name: 'Procédures',
      slug: 'documents-procedures',
      routePath: '/documents/procedures',
      active: true,
      sortOrder: 243,
    },
    { name: 'Tapis ROMUS', slug: 'tapis-romus', routePath: '/tapis-romus', active: true, sortOrder: 60 },
    { name: 'Contrôle caisse', slug: 'controle-caisse', routePath: '/controle-caisse', active: true, sortOrder: 25 },
    {
      name: "Demande d'acompte",
      slug: 'demandes-acompte',
      routePath: '/demandes-acompte',
      active: true,
      sortOrder: 26,
    },
    { name: 'Remise de chèques', slug: 'remise-cheques', routePath: '/remise-cheques', active: true, sortOrder: 27 },
    { name: 'Administration', slug: 'administration', routePath: '/administration', active: true, sortOrder: 20 },
  ],
  menuGroups: [
    { menuKey: 'home', title: 'Accueil', active: true, sortOrder: 0 },
    { menuKey: 'apps', title: 'Applications HUB', active: true, sortOrder: 10 },
    { menuKey: 'accounting', title: 'Comptabilité', active: true, sortOrder: 18 },
    { menuKey: 'documents', title: 'Documents', active: true, sortOrder: 19 },
    { menuKey: 'internal', title: 'Administration', active: true, sortOrder: 20 },
  ],
  menuItems: [
    {
      itemKey: 'module:dashboard',
      groupKey: 'home',
      label: 'Tableau de bord',
      iconKey: 'dashboard',
      active: true,
      sortOrder: 0,
    },
    {
      itemKey: 'module:reservations',
      groupKey: 'apps',
      label: 'Réservations véhicules',
      iconKey: 'truck',
      active: true,
      sortOrder: 10,
    },
    {
      itemKey: 'module:locations-materiel',
      groupKey: 'apps',
      label: 'Location matériel',
      iconKey: 'package',
      active: true,
      sortOrder: 15,
    },
    { itemKey: 'module:equipes', groupKey: 'apps', label: 'Équipe', iconKey: 'users', active: true, sortOrder: 16 },
    { itemKey: 'module:conges', groupKey: 'apps', label: 'Congés & Absences', iconKey: 'calendar', active: true, sortOrder: 17 },
    {
      itemKey: 'module:pilotage-commercial',
      groupKey: 'apps',
      label: 'Pilotage commercial',
      iconKey: 'dashboard',
      active: true,
      sortOrder: 19,
    },
    {
      itemKey: 'module:tournees-representants',
      groupKey: 'apps',
      label: 'Rapport de visite',
      iconKey: 'calendar',
      active: true,
      sortOrder: 18,
    },
    {
      itemKey: 'module:documents-promo',
      groupKey: 'documents',
      label: 'Promo',
      iconKey: 'article',
      active: true,
      sortOrder: 241,
    },
    {
      itemKey: 'module:documents-fiches-techniques',
      groupKey: 'documents',
      label: 'Fiches techniques',
      iconKey: 'article',
      active: true,
      sortOrder: 242,
    },
    {
      itemKey: 'module:documents-procedures',
      groupKey: 'documents',
      label: 'Procédures',
      iconKey: 'article',
      active: true,
      sortOrder: 243,
    },
    {
      itemKey: 'module:tapis-romus',
      groupKey: 'apps',
      label: 'Tapis ROMUS',
      iconKey: 'table',
      active: true,
      sortOrder: 60,
    },
    {
      itemKey: 'module:controle-caisse',
      groupKey: 'accounting',
      label: 'Contrôle caisse',
      iconKey: 'creditCard',
      active: true,
      sortOrder: 10,
    },
    {
      itemKey: 'module:demandes-acompte',
      groupKey: 'accounting',
      label: "Demande d'acompte",
      iconKey: 'banknote',
      active: true,
      sortOrder: 26,
    },
    {
      itemKey: 'module:remise-cheques',
      groupKey: 'accounting',
      label: 'Remise de chèques',
      iconKey: 'creditCard',
      active: true,
      sortOrder: 27,
    },
    {
      itemKey: 'module:administration',
      groupKey: 'internal',
      label: 'Administration',
      iconKey: 'settings',
      active: true,
      sortOrder: 20,
    },
  ],
};

export function installFallbackNavigation(): void {
  window.CRM_NAV_FALLBACK = window.CRM_NAV_FALLBACK || fallbackNavigation;
}
