<?php

namespace Tests\Feature;

use Tests\TestCase;

class CrmFrontendSourceTest extends TestCase
{
    public function test_crm_shell_is_loaded_from_versioned_vite_source(): void
    {
        $blade = (string) file_get_contents(resource_path('views/crm.blade.php'));
        $viteConfig = (string) file_get_contents(base_path('vite.config.js'));
        $shell = (string) file_get_contents(resource_path('frontend/crm/shell.ts'));
        $nativeShell = (string) file_get_contents(resource_path('frontend/crm/layout/native-shell.ts'));
        $legacyTemplate = (string) file_get_contents(resource_path('frontend/crm/legacy/template-compat.ts'));
        $hosts = (string) file_get_contents(resource_path('frontend/crm/modules/hosts.ts'));
        $modules = (string) file_get_contents(resource_path('frontend/crm/modules/register.ts'));
        $menu = (string) file_get_contents(resource_path('frontend/crm/router/menu.ts'));
        $administrationModule = (string) file_get_contents(base_path('Modules/CrmAdministration/resources/assets/crm-administration.js'));
        $loginBlade = (string) file_get_contents(resource_path('views/auth/login.blade.php'));
        $mainActivity = (string) file_get_contents(base_path('mobile/android/app/src/main/java/fr/martinsols/crm/MainActivity.java'));
        $iosBridge = (string) file_get_contents(base_path('mobile/ios/App/App/MartinSolsBridgeViewController.swift'));
        $iosInfoPlist = (string) file_get_contents(base_path('mobile/ios/App/App/Info.plist'));
        $macApp = (string) file_get_contents(base_path('mobile/ios/App/MacApp/MacAppDelegate.swift'));
        $macInfoPlist = (string) file_get_contents(base_path('mobile/ios/App/MacApp/Info.plist'));
        $androidManifest = (string) file_get_contents(base_path('mobile/android/app/src/main/AndroidManifest.xml'));
        $androidBuild = (string) file_get_contents(base_path('mobile/android/app/build.gradle'));
        $androidSettings = (string) file_get_contents(base_path('mobile/android/settings.gradle'));
        $androidSettingsOverride = (string) file_get_contents(base_path('mobile/android/app/src/main/assets/app-settings-override.js'));
        $appDownloadsConfig = (string) file_get_contents(config_path('hub_apps.php'));
        $androidUpdateManifest = json_decode((string) file_get_contents(base_path('mobile/releases/martin-sols-update.json')), true, 512, JSON_THROW_ON_ERROR);
        $androidColors = (string) file_get_contents(base_path('mobile/android/app/src/main/res/values/colors.xml'));
        $androidStyles = (string) file_get_contents(base_path('mobile/android/app/src/main/res/values/styles.xml'));
        $mobilePackage = (string) file_get_contents(base_path('mobile/package.json'));
        $mobilePackageLock = (string) file_get_contents(base_path('mobile/package-lock.json'));
        $mobileApp = (string) file_get_contents(base_path('mobile/src/main.ts'));
        $mobileStyles = (string) file_get_contents(base_path('mobile/src/styles.css'));
        $mobileSettings = (string) file_get_contents(resource_path('frontend/crm/mobile/settings.ts'));
        $capacitorConfig = (string) file_get_contents(base_path('mobile/capacitor.config.json'));
        $openingAnimation = base_path('mobile/src/assets/opening-animation.gif');
        $androidIntroAnimation = base_path('mobile/android/app/src/main/res/raw/intro.gif');
        $openingAnimationHash = 'd965677ac8cab41cdf18f7009171f4d44ab8bc9db23c28ee4aec5b3042f5298b';

        $this->assertStringContainsString("@vite(config('crm_frontend.vite_entries'))", $blade);
        $this->assertStringContainsString('id="crm-shell-config"', $blade);
        $this->assertStringContainsString('<div id="root"></div>', $blade);
        $this->assertStringContainsString('meta name="csrf-token"', $blade);
        $this->assertStringNotContainsString('legacyAdminexScript', $blade);
        $this->assertStringNotContainsString('legacyAdminexStylesheet', $blade);
        $this->assertStringNotContainsString('resources/frontend/adminex/src/main.tsx', $viteConfig);
        $this->assertStringNotContainsString('resources/frontend/adminex/src', $viteConfig);
        $this->assertStringNotContainsString('adminex-ui', $viteConfig);
        $this->assertStringNotContainsString('assets/legacy-adminex.css', $blade);

        $this->assertFileExists(resource_path('frontend/crm/shell.ts'));
        $this->assertFileExists(resource_path('frontend/crm/api/client.ts'));
        $this->assertFileExists(resource_path('frontend/crm/config.ts'));
        $this->assertFileExists(resource_path('frontend/crm/legacy/logout-bridge.ts'));
        $this->assertFileExists(resource_path('frontend/crm/layout/native-shell.ts'));
        $this->assertFileExists(resource_path('frontend/crm/loader.ts'));
        $this->assertFileExists(resource_path('frontend/crm/mobile/embed-bridge.ts'));
        $this->assertFileExists(resource_path('frontend/crm/mobile/fallback-nav.ts'));
        $this->assertFileExists(resource_path('frontend/crm/mobile/settings.ts'));
        $this->assertFileExists(resource_path('frontend/crm/modules/hosts.ts'));
        $this->assertFileExists(resource_path('frontend/crm/router/menu.ts'));
        $this->assertFileExists(resource_path('frontend/crm/styles/shell.css'));
        $this->assertFileExists(resource_path('frontend/crm/styles/native-ui.css'));
        $this->assertFileExists(resource_path('frontend/crm/styles/template-compat.css'));
        $this->assertFileExists(resource_path('frontend/crm/styles/template-compat/variables.css'));
        $this->assertFileExists(resource_path('frontend/crm/styles/template-compat/components.css'));
        $this->assertFileExists(resource_path('frontend/crm/ui/native-ui.ts'));

        $this->assertStringContainsString("import './styles/template-compat.css';", $shell);
        $this->assertStringContainsString("import './styles/shell.css';", $shell);
        $this->assertStringContainsString("import './styles/native-ui.css';", $shell);
        $this->assertStringContainsString('installMartinSolsUi', $shell);
        $this->assertStringContainsString('installCrmModuleHostGuard', $shell);
        $this->assertStringContainsString('installNativeCrmShell', $shell);
        $this->assertStringContainsString('installCurrentCrmModuleRouteLoader', $shell);
        $this->assertStringContainsString('loadCurrentCrmModuleOverlay', $shell);
        $this->assertStringContainsString('preloadRemainingCrmModuleOverlays', $shell);
        $this->assertStringNotContainsString('loadLegacyAdminex()', $shell);
        $this->assertStringContainsString('data-crm-native-shell', $nativeShell);
        $this->assertStringContainsString('layout-sidebar crm-native-sidebar', $nativeShell);
        $this->assertStringContainsString('layout-header crm-native-header', $nativeShell);
        $this->assertStringContainsString('<img class="crm-native-mobile-brand-mark" src="${esc(logoMarkUrl())}" alt="Martin Sols">', $nativeShell);
        $this->assertStringContainsString('<img class="crm-native-mobile-brand-full" src="${esc(logoUrl())}" alt="Martin Sols">', $nativeShell);
        $this->assertStringContainsString('martin-sols-hub-sidebar-collapsed', $nativeShell);
        $this->assertStringContainsString('martin-sols-hub-nav-groups-collapsed', $nativeShell);
        $this->assertStringContainsString('crm-native-sidebar-collapsed', $nativeShell);
        $this->assertStringContainsString('Déployer le menu', $nativeShell);
        $this->assertStringContainsString('Rabattre le menu', $nativeShell);
        $this->assertStringContainsString('isDesktopSidebarMode()', $nativeShell);
        $this->assertStringContainsString('setSidebarCollapsed(readStoredSidebarCollapsed(), false)', $nativeShell);
        $this->assertStringContainsString("fetch('/api/administration?action=profile'", $nativeShell);
        $this->assertStringContainsString('profile.navigation', $nativeShell);
        $this->assertStringContainsString('window.CRM_NAV_FALLBACK = profile.navigation', $nativeShell);
        $this->assertStringContainsString('data-crm-native-submenu-toggle', $nativeShell);
        $this->assertStringContainsString('module.menuBadgeColor', $nativeShell);
        $this->assertStringContainsString('function hexToRgbTriplet', $nativeShell);
        $this->assertStringContainsString('--crm-native-nav-badge-rgb', $nativeShell);
        $this->assertStringContainsString('data-crm-native-nav-group-toggle', $nativeShell);
        $this->assertStringContainsString('data-crm-native-nav-group', $nativeShell);
        $this->assertStringContainsString('data-crm-native-nav-group="${esc(groupKey)}"', $nativeShell);
        $this->assertStringContainsString('function syncActiveNavigationGroups', $nativeShell);
        $this->assertStringContainsString('function readCollapsedNavigationGroups', $nativeShell);
        $this->assertStringContainsString('function setNavigationGroupOpen', $nativeShell);
        $this->assertStringContainsString('const collapsed = collapsedGroups.has(groupKey)', $nativeShell);
        $this->assertStringContainsString('setNavigationGroupOpen(group, open)', $nativeShell);
        $this->assertStringContainsString('storeCurrentNavigationGroupState()', $nativeShell);
        $this->assertStringContainsString('document.querySelectorAll<HTMLElement>(\'[data-crm-native-nav-group]\')', $nativeShell);
        $this->assertStringContainsString('function childrenByParentItem', $nativeShell);
        $this->assertStringContainsString('function menuItemWithChildrenHtml', $nativeShell);
        $this->assertStringContainsString('data-crm-native-nav-branch', $nativeShell);
        $this->assertStringContainsString('crm-native-nav-branch-link', $nativeShell);
        $this->assertStringContainsString('crm-native-nav-branch-toggle', $nativeShell);
        $this->assertStringContainsString('crm:navigation-refresh', $nativeShell);
        $this->assertStringContainsString('loadProfile({ force: true })', $nativeShell);
        $this->assertStringContainsString("item.itemKey.startsWith('admin:')", $nativeShell);
        $this->assertStringContainsString('!parentItemKey(item)', $nativeShell);
        $this->assertStringNotContainsString("itemKey: 'admin:overview'", $nativeShell);
        $this->assertStringNotContainsString('Vue d\'ensemble', $nativeShell);
        $this->assertStringContainsString('iconForKey', $nativeShell);
        $this->assertStringContainsString("iconForKey('logout')", $nativeShell);
        $this->assertStringContainsString('crm-native-nav-label">Se déconnecter', $nativeShell);
        $this->assertStringContainsString('data-crm-mobile-settings-toggle', $nativeShell);
        $this->assertStringContainsString('Paramètres de l’app', $nativeShell);
        $this->assertStringContainsString('window.MartinSolsCrmConfig?.mobile.app === true', $nativeShell);
        $this->assertStringContainsString('Boolean(window.MartinSolsNativeApp)', $nativeShell);
        $this->assertStringContainsString('href="/">Tableau de bord</a>', $nativeShell);
        $this->assertStringContainsString('crm-native-brand" href="/"', $nativeShell);
        $this->assertStringContainsString('const active = isNavigationItemActive(parentPath);', $nativeShell);
        $this->assertStringContainsString('const childActive = children.some((child: CrmMenuItem) => menuItemTreeIsActive(child, routes, childrenByParent));', $nativeShell);
        $this->assertStringContainsString('const open = active || childActive;', $nativeShell);
        $this->assertStringContainsString('const active = isNavigationItemActive(link.getAttribute(\'href\') || \'#\');', $nativeShell);
        $this->assertStringNotContainsString('crm-native-nav-group-nested', $nativeShell);
        $this->assertStringNotContainsString('function isSubmenuGroup', $nativeShell);
        $this->assertStringContainsString('isLegacyTemplateRoute()', $legacyTemplate);
        $this->assertStringContainsString('return false;', $legacyTemplate);
        $this->assertStringNotContainsString('appendModuleScript', $legacyTemplate);
        $this->assertStringNotContainsString('legacyAdminexStylesheet', $legacyTemplate);

        $this->assertStringContainsString("id: 'crm-sales-tours-module'", $hosts);
        $this->assertStringContainsString("paths: ['/rapport-visite', '/tournees-representants']", $hosts);
        $this->assertStringContainsString("id: 'crm-reservations-module'", $hosts);
        $this->assertStringContainsString("id: 'crm-equipment-rentals-module'", $hosts);
        $this->assertStringContainsString("id: 'crm-administration-module'", $hosts);
        $this->assertStringContainsString("id: 'crm-tapis-romus-module'", $hosts);
        $this->assertStringNotContainsString('adminexOnly', $hosts);
        $this->assertStringContainsString("prefix: '/documents/'", $hosts);
        $this->assertStringContainsString('refreshStaleRouteOnce', $hosts);
        $this->assertStringContainsString('refreshMissingHostOnce', $hosts);
        $this->assertStringContainsString('scheduleMissingHostRefresh', $hosts);
        $this->assertStringContainsString('clearCrmRuntimeCaches', $hosts);

        $this->assertStringContainsString("administration: () => import('../../../../Modules/CrmAdministration/resources/assets/crm-administration.js')", $modules);
        $this->assertStringContainsString("equipmentRentals: () => import('../../../../Modules/CrmEquipmentRentals/resources/assets/crm-equipment-rentals.js')", $modules);
        $this->assertStringContainsString("reservations: () => import('../../../../Modules/CrmReservations/resources/assets/crm-reservations.js')", $modules);
        $this->assertStringContainsString("{ name: 'Tableau de bord', slug: 'dashboard', routePath: '/', active: true, sortOrder: 0 }", $menu);
        $this->assertStringContainsString("menuBadgeColor: '#95002e'", $menu);
        $this->assertStringContainsString("tapisRomus: () => import('../../../../Modules/CrmTapisRomus/resources/assets/crm-tapis-romus.js')", $modules);
        $this->assertStringContainsString("cashControl: () => import('../../../../Modules/CrmCashControl/resources/assets/crm-controle-caisse.js')", $modules);
        $this->assertStringNotContainsString('mountLegacyReactComponent', $modules);
        $this->assertStringNotContainsString('loadLegacyAsset', $modules);
        $this->assertStringNotContainsString('transitionalReactModules', $modules);
        $this->assertStringNotContainsString('import(/* @vite-ignore */ `/assets/', $modules);
        $this->assertStringContainsString('["reservations", "Réservations", "Véhicules", "truck"]', $administrationModule);
        $this->assertStringContainsString('["equipment", "Location matériel", "Matériel et catégories", "package"]', $administrationModule);
        $this->assertStringContainsString('data-vehicle-form', $administrationModule);
        $this->assertStringContainsString('save_vehicle', $administrationModule);
        $this->assertStringContainsString('delete_vehicle', $administrationModule);
        $this->assertStringContainsString('data-equipment-category-form', $administrationModule);
        $this->assertStringContainsString('save_equipment_category', $administrationModule);
        $this->assertStringContainsString('delete_equipment_category', $administrationModule);
        $this->assertStringContainsString('data-equipment-item-form', $administrationModule);
        $this->assertStringContainsString('save_equipment_item', $administrationModule);
        $this->assertStringContainsString('delete_equipment_item', $administrationModule);
        $this->assertStringContainsString('menuBadgeColor', $administrationModule);
        $this->assertStringContainsString('Couleur badge', $administrationModule);

        $this->assertFileDoesNotExist(resource_path('frontend/crm/legacy/react-components.ts'));
        $this->assertDirectoryDoesNotExist(resource_path('frontend/adminex'));
        $this->assertFileDoesNotExist(resource_path('frontend/static/assets/index-CqSzWeas.js'));
        $this->assertFileDoesNotExist(resource_path('frontend/static/assets/legacy-adminex.css'));

        $mobileFallback = (string) file_get_contents(resource_path('frontend/crm/mobile/fallback-nav.ts'));
        $shellCss = (string) file_get_contents(resource_path('frontend/crm/styles/shell.css'));
        $templateCompatCss = (string) file_get_contents(resource_path('frontend/crm/styles/template-compat.css'));
        $templateVariablesCss = (string) file_get_contents(resource_path('frontend/crm/styles/template-compat/variables.css'));
        $templateComponentsCss = (string) file_get_contents(resource_path('frontend/crm/styles/template-compat/components.css'));
        $nativeUi = (string) file_get_contents(resource_path('frontend/crm/ui/native-ui.ts'));
        $nativeUiCss = (string) file_get_contents(resource_path('frontend/crm/styles/native-ui.css'));
        $filamentCss = (string) file_get_contents(public_path('css/filament/crm-filament.css'));

        $this->assertStringContainsString("window.matchMedia('(max-width: 767.98px)')", $mobileFallback);
        $this->assertStringContainsString('--color-secondary-50: #fafafa;', $templateVariablesCss);
        $this->assertStringContainsString('background: var(--color-secondary-50, #fafafa);', $shellCss);
        $this->assertStringContainsString('--crm-martin-yellow: #f7b711;', $shellCss);
        $this->assertStringContainsString('.crm-native-nav-subitems .crm-native-nav-link.crm-native-nav-subitem.is-active', $shellCss);
        $this->assertStringContainsString('--crm-native-nav-badge-rgb: var(--theme-primary);', $shellCss);
        $this->assertStringContainsString('background: rgb(var(--crm-native-nav-badge-rgb) / 0.1);', $shellCss);
        $this->assertStringContainsString('color: rgb(var(--crm-native-nav-badge-rgb));', $shellCss);
        $this->assertStringContainsString('color: var(--crm-martin-yellow);', $shellCss);
        $this->assertStringContainsString('.crm-native-nav-group.is-collapsed .crm-native-nav-group-body', $shellCss);
        $this->assertStringContainsString('body.crm-native-sidebar-collapsed .crm-native-nav-group-body', $shellCss);
        $this->assertStringContainsString('.crm-native-nav-section-chevron', $shellCss);
        $this->assertStringContainsString('--ms-ui-soft: var(--color-secondary-50, #fafafa);', $nativeUiCss);
        $this->assertStringContainsString('--crm-bg: #fafafa;', $filamentCss);
        $this->assertStringNotContainsString('#eff2f5', $templateVariablesCss.$shellCss.$nativeUiCss.$filamentCss);
        $this->assertStringContainsString('shouldUseFallbackNavigation', $mobileFallback);
        $this->assertStringContainsString("document.body.classList.contains('crm-mobile-app')", $mobileFallback);
        $this->assertStringContainsString("document.body.classList.contains('crm-mobile-embed')", $mobileFallback);
        $this->assertStringContainsString('new MutationObserver', $mobileFallback);
        $this->assertStringNotContainsString("if (!document.body.classList.contains('crm-mobile-app'))", $mobileFallback);
        $this->assertStringContainsString("if (document.body.classList.contains('crm-mobile-app'))", $mobileFallback);
        $this->assertStringContainsString('return false;', $mobileFallback);
        $this->assertStringNotContainsString("window.matchMedia('(display-mode: standalone)')", $mobileFallback);
        $this->assertStringContainsString("'<a class=\"crm-mobile-fallback-brand\" href=\"/\">'", $mobileFallback);
        $this->assertStringContainsString('body.crm-mobile-fallback-nav-browser', $shellCss);
        $this->assertStringNotContainsString('html:has(body.crm-mobile-app)', $shellCss);
        $this->assertStringNotContainsString('overscroll-behavior-y: none;', $shellCss);
        $this->assertStringNotContainsString('--crm-mobile-app-header-height: var(--crm-header-height);', $shellCss);
        $this->assertStringNotContainsString('--crm-mobile-app-safe-top:', $shellCss);
        $this->assertStringNotContainsString('--crm-mobile-app-status-background:', $shellCss);
        $this->assertStringContainsString('body.crm-mobile-app .crm-native-main', $shellCss);
        $this->assertStringContainsString('body.crm-mobile-app .crm-native-header', $shellCss);
        $this->assertStringContainsString('--sidebar-collapsed-width: 80px;', $shellCss);
        $this->assertStringContainsString('body.crm-native-sidebar-collapsed .crm-native-sidebar', $shellCss);
        $this->assertStringContainsString('body.crm-native-sidebar-collapsed .crm-native-body', $shellCss);
        $this->assertStringContainsString('body.crm-native-sidebar-collapsed .crm-native-header', $shellCss);
        $this->assertStringContainsString('body.crm-native-sidebar-collapsed .crm-native-nav-submenu:hover .crm-native-nav-subitems', $shellCss);
        $this->assertStringContainsString('body.crm-native-sidebar-collapsed .crm-native-brand-mark', $shellCss);
        $this->assertStringContainsString('width: 2.45rem;', $shellCss);
        $this->assertStringContainsString('height: 2.45rem;', $shellCss);
        $this->assertStringContainsString('position: sticky;', $shellCss);
        $this->assertStringContainsString('padding-top: var(--crm-header-height);', $shellCss);
        $this->assertStringContainsString('height: var(--crm-header-height);', $shellCss);
        $this->assertStringContainsString('padding: 0 0.75rem;', $shellCss);
        $this->assertStringNotContainsString('padding: 0 0.75rem !important;', $shellCss);
        $this->assertStringContainsString('flex: 0 1 clamp(7rem, 22vw, 9.25rem);', $shellCss);
        $this->assertStringContainsString('body.crm-native-sidebar-open .crm-native-mobile-brand-full', $shellCss);
        $this->assertStringContainsString('@media (max-width: 767px)', $shellCss);
        $this->assertStringContainsString('flex: 0 0 2.4rem;', $shellCss);
        $this->assertStringContainsString('max-width: clamp(10rem, 44vw, 12rem) !important;', $shellCss);
        $this->assertStringContainsString('flex-basis: clamp(9.6rem, 44vw, 10.8rem) !important;', $shellCss);
        $this->assertStringNotContainsString('width: min(118px, 30vw);', $shellCss);
        $this->assertStringNotContainsString('max-width: 6.9rem !important;', $shellCss);
        $this->assertStringNotContainsString('max-width: 6.1rem !important;', $shellCss);
        $this->assertStringContainsString('body.crm-mobile-app .crm-mobile-fallback-header', $shellCss);
        $this->assertStringContainsString('display: none !important;', $shellCss);
        $this->assertStringNotContainsString('z-index: 9988;', $shellCss);
        $this->assertStringNotContainsString('injectMobileHeaderPatch', $mainActivity);
        $this->assertStringNotContainsString('injectMobileHeaderReset', $mainActivity);
        $this->assertStringNotContainsString('stripCrmAppShellMode', $mainActivity);
        $this->assertStringNotContainsString('scheduleCrmAppShellCleanup', $mainActivity);
        $this->assertStringNotContainsString('martin-sols-webview-clean-slate', $mainActivity);
        $this->assertStringNotContainsString('view.evaluateJavascript', $mainActivity);
        $this->assertStringNotContainsString('BridgeActivity', $mainActivity);
        $this->assertStringNotContainsString('com.getcapacitor', $mainActivity);
        $this->assertStringNotContainsString('WindowCompat', $mainActivity);
        $this->assertStringNotContainsString('SPLASH_URL', $mainActivity);
        $this->assertStringNotContainsString('configureSplashWebView', $mainActivity);
        $this->assertStringNotContainsString('setMediaController', $mainActivity);
        $this->assertStringNotContainsString('VideoView', $mainActivity);
        $this->assertStringContainsString('public class MainActivity extends Activity', $mainActivity);
        $this->assertStringContainsString('private static final String HUB_URL = "https://crm.jp2.fr/?mobile_app=1";', $mainActivity);
        $this->assertStringContainsString('private static final String UPDATE_MANIFEST_URL = "https://raw.githubusercontent.com/jp2creation/hub_android/main/releases/jp2-hub-android-update.json";', $mainActivity);
        $this->assertStringContainsString('private static final String UPDATE_MANIFEST_API_URL = "https://api.github.com/repos/jp2creation/hub_android/contents/releases/jp2-hub-android-update.json?ref=main";', $mainActivity);
        $this->assertStringContainsString('private static let updateManifestUrl = URL(string: "https://raw.githubusercontent.com/jp2creation/hub_apple/main/releases/martin-sols-update.json")!', $iosBridge);
        $this->assertStringContainsString('private static let updateManifestUrl = URL(string: "https://raw.githubusercontent.com/jp2creation/hub_apple/main/releases/martin-sols-update.json")!', $macApp);
        $this->assertStringContainsString('private static let splashDuration: TimeInterval = 5.5', $macApp);
        $this->assertStringContainsString('private static final String APK_MIME_TYPE = "application/vnd.android.package-archive";', $mainActivity);
        $this->assertStringContainsString('private static final long SPLASH_DURATION_MS = 5500L;', $mainActivity);
        $this->assertStringContainsString('private static final long UPDATE_CHECK_DELAY_MS = 1500L;', $mainActivity);
        $this->assertStringContainsString('private static final long UPDATE_PROGRESS_INTERVAL_MS = 450L;', $mainActivity);
        $this->assertStringContainsString('private static final int SPLASH_ANIMATION_RESOURCE = R.raw.intro;', $mainActivity);
        $this->assertStringNotContainsString('INTRO_ANIMATION_WIDTH_FRACTION', $mainActivity);
        $this->assertStringNotContainsString('INTRO_ANIMATION_HEIGHT_FRACTION', $mainActivity);
        $this->assertStringNotContainsString('INTRO_ANIMATION_MAX_WIDTH_DP', $mainActivity);
        $this->assertStringContainsString('private static final int UPDATE_PROGRESS_MAX = 100;', $mainActivity);
        $this->assertStringContainsString('private static final long NATIVE_LOCATION_TIMEOUT_MS = 15000L;', $mainActivity);
        $this->assertStringContainsString('requestWindowFeature(Window.FEATURE_NO_TITLE);', $mainActivity);
        $this->assertStringContainsString('rootView = new FrameLayout(this);', $mainActivity);
        $this->assertStringContainsString('webView = new WebView(this);', $mainActivity);
        $this->assertStringContainsString('splashLayer = new FrameLayout(this);', $mainActivity);
        $this->assertStringContainsString('splashLayer.setBackgroundColor(SPLASH_BACKGROUND);', $mainActivity);
        $this->assertStringContainsString('splashView = new IntroGifView(this);', $mainActivity);
        $this->assertStringContainsString('configureSplashGifView(splashView);', $mainActivity);
        $this->assertStringNotContainsString('view.setBackgroundColor(SPLASH_BACKGROUND);', $mainActivity);
        $this->assertStringContainsString('rootView.addView(splashLayer, matchParentLayoutParams());', $mainActivity);
        $this->assertStringContainsString('webView.loadUrl(HUB_URL);', $mainActivity);
        $this->assertStringContainsString('handler.postDelayed(hideSplash, SPLASH_DURATION_MS);', $mainActivity);
        $this->assertStringContainsString('window.setDecorFitsSystemWindows(true);', $mainActivity);
        $this->assertStringContainsString('private static final int MARTIN_SOLS_RED = Color.rgb(149, 0, 46);', $mainActivity);
        $this->assertStringContainsString('private static final int MARTIN_SOLS_BACKGROUND = Color.rgb(245, 247, 251);', $mainActivity);
        $this->assertStringContainsString('window.setStatusBarColor(MARTIN_SOLS_RED);', $mainActivity);
        $this->assertStringContainsString('protected void onResume()', $mainActivity);
        $this->assertStringContainsString('view.setOverScrollMode(View.OVER_SCROLL_NEVER);', $mainActivity);
        $this->assertStringNotContainsString('SYSTEM_UI_FLAG_LIGHT_STATUS_BAR', $mainActivity);
        $this->assertStringContainsString('if (isWebUrl(request.getUrl()))', $mainActivity);
        $this->assertStringContainsString('public boolean shouldOverrideUrlLoading(WebView view, String url)', $mainActivity);
        $this->assertStringContainsString('private boolean isWebUrl(Uri uri)', $mainActivity);
        $this->assertStringContainsString('settings.setJavaScriptEnabled(true);', $mainActivity);
        $this->assertStringContainsString('settings.setGeolocationEnabled(true);', $mainActivity);
        $this->assertStringNotContainsString('settings.setGeolocationEnabled(false);', $mainActivity);
        $this->assertStringContainsString('onGeolocationPermissionsShowPrompt', $mainActivity);
        $this->assertStringContainsString('GeolocationPermissions.Callback', $mainActivity);
        $this->assertStringContainsString('LocationManager', $mainActivity);
        $this->assertStringContainsString('private void requestNativeLocation(String requestId, boolean highAccuracy)', $mainActivity);
        $this->assertStringContainsString('private void dispatchNativeLocationResult(String requestId, Location location, String error)', $mainActivity);
        $this->assertStringContainsString('martin-sols:native-location-result', $mainActivity);
        $this->assertStringContainsString('requestInitialLocationPermission()', $mainActivity);
        $this->assertStringContainsString('BiometricPrompt.Builder', $mainActivity);
        $this->assertStringContainsString('KeyguardManager', $mainActivity);
        $this->assertStringContainsString('MOBILE_AUTH_KEY_ALIAS', $mainActivity);
        $this->assertStringContainsString('private volatile boolean trustedCrmPageActive;', $mainActivity);
        $this->assertStringContainsString('private void updateTrustedCrmPage(String url)', $mainActivity);
        $this->assertStringContainsString('trustedCrmPageActive = isTrustedCrmOrigin(url);', $mainActivity);
        $this->assertStringContainsString('return trustedCrmPageActive;', $mainActivity);
        $this->assertStringContainsString('saveMobileSessionPayload', $mainActivity);
        $this->assertStringContainsString('authenticateSavedMobileSession', $mainActivity);
        $this->assertStringContainsString('getMobileAuthStatus', $mainActivity);
        $this->assertStringContainsString('clearMobileSession', $mainActivity);
        $this->assertStringContainsString('view.setOnTouchListener(new View.OnTouchListener()', $mainActivity);
        $this->assertStringContainsString('Movie.decodeStream(inputStream)', $mainActivity);
        $this->assertStringContainsString('animation.setTime((int) ((now - animationStartMs) % duration));', $mainActivity);
        $this->assertStringContainsString('postInvalidateOnAnimation();', $mainActivity);
        $this->assertStringNotContainsString('view.setSurfaceTextureListener(new TextureView.SurfaceTextureListener()', $mainActivity);
        $this->assertStringNotContainsString('splashPlayer = new MediaPlayer();', $mainActivity);
        $this->assertStringContainsString('rootView.removeView(layer);', $mainActivity);
        $this->assertStringContainsString('private void showCrmWebView()', $mainActivity);
        $this->assertStringContainsString('webView.bringToFront();', $mainActivity);
        $this->assertStringContainsString('webView.invalidate();', $mainActivity);
        $this->assertStringContainsString('webView.loadUrl(HUB_URL);', $mainActivity);
        $this->assertStringContainsString('setMeasuredDimension(viewWidth, viewHeight);', $mainActivity);
        $this->assertStringContainsString('float scale = Math.max(getWidth() / animationWidth, getHeight() / animationHeight);', $mainActivity);
        $this->assertStringContainsString('private void scheduleUpdateCheck()', $mainActivity);
        $this->assertStringContainsString('view.addJavascriptInterface(new MartinSolsNativeAppBridge(), "MartinSolsNativeApp")', $mainActivity);
        $this->assertStringContainsString('import android.webkit.JavascriptInterface;', $mainActivity);
        $this->assertStringContainsString('private void checkForAppUpdate(boolean notifyWhenCurrent)', $mainActivity);
        $this->assertStringContainsString('private AppUpdate fetchAppUpdate()', $mainActivity);
        $this->assertStringContainsString('JSONObject manifest = new JSONObject(readText(connection.getInputStream()));', $mainActivity);
        $this->assertStringContainsString('update.versionCode <= BuildConfig.VERSION_CODE', $mainActivity);
        $this->assertStringContainsString('private void showNoUpdateDialog()', $mainActivity);
        $this->assertStringContainsString('private final class MartinSolsNativeAppBridge', $mainActivity);
        $this->assertStringContainsString('checkForAppUpdate(true)', $mainActivity);
        $this->assertStringContainsString('private void showUpdateDialog(AppUpdate update)', $mainActivity);
        $this->assertStringContainsString('private void startUpdateDownload(AppUpdate update)', $mainActivity);
        $this->assertStringContainsString('private void showUpdateProgressDialog(AppUpdate update)', $mainActivity);
        $this->assertStringContainsString('private void pollUpdateDownloadProgress()', $mainActivity);
        $this->assertStringContainsString('private void updateProgressUi(String message, int progress, boolean indeterminate)', $mainActivity);
        $this->assertStringContainsString('private void showUpdateFailure(String message)', $mainActivity);
        $this->assertStringContainsString('private void cancelActiveUpdateDownload(boolean showMessage)', $mainActivity);
        $this->assertStringContainsString('DownloadManager.Query query = new DownloadManager.Query();', $mainActivity);
        $this->assertStringContainsString('query.setFilterById(updateDownloadId);', $mainActivity);
        $this->assertStringContainsString('DownloadManager.COLUMN_BYTES_DOWNLOADED_SO_FAR', $mainActivity);
        $this->assertStringContainsString('DownloadManager.COLUMN_TOTAL_SIZE_BYTES', $mainActivity);
        $this->assertStringContainsString('DownloadManager.STATUS_SUCCESSFUL', $mainActivity);
        $this->assertStringContainsString('DownloadManager.STATUS_FAILED', $mainActivity);
        $this->assertStringContainsString('DownloadManager.STATUS_PAUSED', $mainActivity);
        $this->assertStringContainsString('updateProgressBar.setIndeterminate(true);', $mainActivity);
        $this->assertStringContainsString('progress + " %"', $mainActivity);
        $this->assertStringContainsString('Mise a jour interrompue', $mainActivity);
        $this->assertStringContainsString('Autorisation Android requise', $mainActivity);
        $this->assertStringContainsString('Autorisation non accordee', $mainActivity);
        $this->assertStringContainsString('Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES', $mainActivity);
        $this->assertStringContainsString('Settings.ACTION_BIOMETRIC_ENROLL', $mainActivity);
        $this->assertStringContainsString('Settings.ACTION_SECURITY_SETTINGS', $mainActivity);
        $this->assertStringContainsString('Settings.ACTION_SETTINGS', $mainActivity);
        $this->assertStringContainsString('private AppUpdate fetchAppUpdateFromUrl(String manifestUrl, boolean githubContentsResponse)', $mainActivity);
        $this->assertStringContainsString('connection.setUseCaches(false);', $mainActivity);
        $this->assertStringContainsString('connection.setRequestProperty("Cache-Control", "no-cache");', $mainActivity);
        $this->assertStringContainsString('connection.setRequestProperty("User-Agent", "Martin-Sols-Android/" + BuildConfig.VERSION_NAME);', $mainActivity);
        $this->assertStringContainsString('private JSONObject decodeGitHubContentsManifest(JSONObject response)', $mainActivity);
        $this->assertStringContainsString('Base64.decode(encodedContent, Base64.DEFAULT)', $mainActivity);
        $this->assertStringContainsString('DownloadManager.Request request = new DownloadManager.Request(Uri.parse(update.apkUrl));', $mainActivity);
        $this->assertStringContainsString('DownloadManager.ACTION_DOWNLOAD_COMPLETE', $mainActivity);
        $this->assertStringContainsString('downloadManager.getUriForDownloadedFile(updateDownloadId)', $mainActivity);
        $this->assertStringContainsString('pendingUpdateSha256.equalsIgnoreCase(downloadedSha256)', $mainActivity);
        $this->assertStringContainsString('MessageDigest.getInstance("SHA-256")', $mainActivity);
        $this->assertStringContainsString('MOBILE_AUTH_APP_CODE_HASH', $mainActivity);
        $this->assertStringContainsString('PBKDF2WithHmacSHA256', $mainActivity);
        $this->assertStringContainsString('private void showSetAppCodeDialog()', $mainActivity);
        $this->assertStringContainsString('private void showAppCodePrompt(String requestId)', $mainActivity);
        $this->assertStringContainsString('private boolean openDeviceSecuritySettings()', $mainActivity);
        $this->assertStringContainsString('private boolean openSettingsActivity(String action)', $mainActivity);
        $this->assertStringContainsString('public String setAppCode()', $mainActivity);
        $this->assertStringContainsString('public String clearAppCode()', $mainActivity);
        $this->assertStringContainsString('public String openDeviceSecuritySettings()', $mainActivity);
        $this->assertStringContainsString('public String requestLocation(String requestId, boolean highAccuracy)', $mainActivity);
        $this->assertStringContainsString('private String runTrustedNativeAction(Runnable action, String message)', $mainActivity);
        $this->assertStringContainsString('if (!MainActivity.this.openDeviceSecuritySettings())', $mainActivity);
        $this->assertStringContainsString('private void showNativeActionFailure(String message)', $mainActivity);
        $this->assertStringContainsString('setTitle("Action impossible")', $mainActivity);
        $this->assertStringContainsString('private String nativeActionResult(boolean ok, String message)', $mainActivity);
        $this->assertStringContainsString('APP_SETTINGS_OVERRIDE_ASSET = "app-settings-override.js"', $mainActivity);
        $this->assertStringContainsString('private void injectAppSettingsOverride(WebView targetWebView)', $mainActivity);
        $this->assertStringContainsString('targetWebView.evaluateJavascript(readText(getAssets().open(APP_SETTINGS_OVERRIDE_ASSET)), null)', $mainActivity);
        $this->assertStringContainsString('public void onPageFinished(WebView view, String url)', $mainActivity);
        $this->assertStringContainsString('updateTrustedCrmPage(url);', $mainActivity);
        $this->assertStringContainsString('injectAppSettingsOverride(view);', $mainActivity);
        $this->assertStringContainsString('window.MartinSolsAndroidSettingsOverride', $androidSettingsOverride);
        $this->assertStringContainsString('data-crm-mobile-settings-toggle', $androidSettingsOverride);
        $this->assertStringContainsString('stopImmediatePropagation', $androidSettingsOverride);
        $this->assertStringContainsString('data-martin-sols-native-settings', $androidSettingsOverride);
        $this->assertStringContainsString('ms-native-settings-group', $androidSettingsOverride);
        $this->assertStringNotContainsString('ms-native-settings-methods', $androidSettingsOverride);
        $this->assertStringContainsString('Paramétrage de l’application', $androidSettingsOverride);
        $this->assertStringContainsString('Sécurité de l’appareil', $androidSettingsOverride);
        $this->assertStringContainsString('Code app Martin Sols', $androidSettingsOverride);
        $this->assertStringContainsString('Activer la connexion rapide', $androidSettingsOverride);
        $this->assertStringContainsString('/api/mobile/native-session', $androidSettingsOverride);
        $this->assertStringContainsString('function requestNativeLocation()', $androidSettingsOverride);
        $this->assertStringContainsString('nativeBridge.requestLocation(requestId, Boolean(settings.highAccuracyLocation))', $androidSettingsOverride);
        $this->assertStringContainsString('Localisation terrain', $androidSettingsOverride);
        $this->assertStringContainsString('Rechercher une mise à jour', $androidSettingsOverride);
        $this->assertStringContainsString("callNative('checkForUpdates'", $androidSettingsOverride);
        $this->assertStringContainsString("callNative('setAppCode'", $androidSettingsOverride);
        $this->assertStringContainsString("callNative('openDeviceSecuritySettings'", $androidSettingsOverride);
        $this->assertStringContainsString("callNative('clearAppCode'", $androidSettingsOverride);
        $this->assertStringContainsString("callNative('clearMobileSession'", $androidSettingsOverride);
        $this->assertStringContainsString('function nativeResult(value)', $androidSettingsOverride);
        $this->assertStringContainsString('result.ok === false', $androidSettingsOverride);
        $this->assertStringContainsString('private static final class AppUpdate', $mainActivity);
        $this->assertStringContainsString('ACCESS_FINE_LOCATION', $androidManifest);
        $this->assertStringContainsString('ACCESS_COARSE_LOCATION', $androidManifest);
        $this->assertStringContainsString('USE_BIOMETRIC', $androidManifest);
        $this->assertStringContainsString('hardware.location.gps', $androidManifest);
        $this->assertStringContainsString('REQUEST_INSTALL_PACKAGES', $androidManifest);
        $this->assertStringNotContainsString('@capacitor/geolocation', $mobilePackage);
        $this->assertStringNotContainsString('@capacitor/geolocation', $mobilePackageLock);
        $this->assertStringNotContainsString('@capacitor/device', $mobilePackage);
        $this->assertStringNotContainsString('@capacitor/device', $mobilePackageLock);
        $this->assertStringNotContainsString('@capacitor/network', $mobilePackage);
        $this->assertStringNotContainsString('@capacitor/network', $mobilePackageLock);
        $this->assertStringNotContainsString('@capacitor/preferences', $mobilePackage);
        $this->assertStringNotContainsString('@capacitor/preferences', $mobilePackageLock);
        $this->assertFileExists($openingAnimation);
        $this->assertFileDoesNotExist(base_path('mobile/src/assets/opening-animation.mp4'));
        $this->assertSame($openingAnimationHash, hash_file('sha256', $openingAnimation));
        $this->assertFileExists($androidIntroAnimation);
        $this->assertFileDoesNotExist(base_path('mobile/android/app/src/main/assets/intro.mp4'));
        $this->assertFileDoesNotExist(base_path('mobile/android/app/src/main/res/raw/intro.mp4'));
        $this->assertFileExists(base_path('mobile/android/app/src/main/assets/app-settings-override.js'));
        $this->assertSame($openingAnimationHash, hash_file('sha256', $androidIntroAnimation));
        $this->assertFileDoesNotExist(base_path('mobile/android/app/src/main/assets/splash.html'));
        $this->assertFileDoesNotExist(base_path('mobile/android/app/src/main/res/drawable/splash.png'));
        $this->assertFileDoesNotExist(base_path('mobile/android/app/src/main/res/layout/activity_main.xml'));
        $this->assertFileDoesNotExist(base_path('mobile/android/app/src/main/res/xml/config.xml'));
        $this->assertFileDoesNotExist(base_path('mobile/android/app/src/main/res/xml/file_paths.xml'));
        $this->assertStringContainsString("const openingAnimationUrl = new URL('./assets/opening-animation.gif', import.meta.url).href", $mobileApp);
        $this->assertStringContainsString("const defaultCrmUrl = 'https://crm.jp2.fr/?mobile_app=1&source=ios_app'", $mobileApp);
        $this->assertStringContainsString('function normalizeCrmUrl(value: string): string', $mobileApp);
        $this->assertStringContainsString("url.searchParams.set('mobile_app', '1')", $mobileApp);
        $this->assertStringContainsString('const openingAnimationDurationMs = 5500', $mobileApp);
        $this->assertStringContainsString('const startupIntro = renderStartup()', $mobileApp);
        $this->assertStringContainsString('class="startup-intro-media"', $mobileApp);
        $this->assertStringContainsString('const animationTimer = window.setTimeout(finish, openingAnimationDurationMs)', $mobileApp);
        $this->assertStringContainsString("introImage.addEventListener('error', complete, { once: true })", $mobileApp);
        $this->assertStringContainsString('function openCrmWebView(): void', $mobileApp);
        $this->assertStringContainsString('window.location.replace(crmUrl)', $mobileApp);
        $this->assertStringNotContainsString('/api/mobile', $mobileApp);
        $this->assertStringNotContainsString('redirectPath', $mobileApp);
        $this->assertStringNotContainsString('plain: true', $mobileApp);
        $this->assertStringNotContainsString('renderLogin', $mobileApp);
        $this->assertStringNotContainsString('data-open-settings', $mobileApp);
        $this->assertStringNotContainsString('Geolocation', $mobileApp);
        $this->assertStringNotContainsString('CapacitorHttp', $mobileApp);
        $this->assertStringContainsString("document.documentElement.classList.add('crm-native-handoff')", $mobileApp);
        $this->assertStringContainsString("app.innerHTML = ''", $mobileApp);
        $this->assertStringContainsString('versionCode 56', $androidBuild);
        $this->assertStringContainsString('versionName "1.54"', $androidBuild);
        $this->assertStringContainsString('buildConfig = true', $androidBuild);
        $this->assertStringContainsString('MARTIN_SOLS_ANDROID_KEYSTORE_PATH', $androidBuild);
        $this->assertStringContainsString('MARTIN_SOLS_ANDROID_KEYSTORE_PASSWORD', $androidBuild);
        $this->assertStringContainsString('MARTIN_SOLS_ANDROID_KEY_ALIAS', $androidBuild);
        $this->assertStringContainsString('MARTIN_SOLS_ANDROID_KEY_PASSWORD', $androidBuild);
        $this->assertStringNotContainsString('capacitor', $androidSettings);
        $this->assertStringNotContainsString('capacitor', $androidBuild);
        $this->assertStringNotContainsString('appcompat', $androidBuild);
        $this->assertStringNotContainsString('core-splashscreen', $androidBuild);
        $this->assertSame(1, $androidUpdateManifest['schemaVersion']);
        $this->assertSame('Martin Sols', $androidUpdateManifest['appName']);
        $this->assertSame('https://github.com/jp2creation/hub_android', $androidUpdateManifest['repositories']['android']);
        $this->assertSame('https://github.com/jp2creation/hub_apple', $androidUpdateManifest['repositories']['apple']);
        $this->assertSame('https://github.com/jp2creation/hub_windows', $androidUpdateManifest['repositories']['windows']);
        $this->assertIsInt($androidUpdateManifest['android']['versionCode']);
        $this->assertGreaterThanOrEqual(38, $androidUpdateManifest['android']['versionCode']);
        $this->assertMatchesRegularExpression('/^1\\.\\d+$/', $androidUpdateManifest['android']['versionName']);
        $this->assertSame('https://raw.githubusercontent.com/jp2creation/hub_android/main/releases/jp2-hub-android-update.json', $androidUpdateManifest['android']['manifestUrl']);
        $this->assertStringStartsWith('https://github.com/jp2creation/hub_android/releases/download/hub-android-v', $androidUpdateManifest['android']['apkUrl']);
        $this->assertStringContainsString('/Martin_Sols_', $androidUpdateManifest['android']['apkUrl']);
        $this->assertMatchesRegularExpression('/^[a-f0-9]{64}$/', $androidUpdateManifest['android']['sha256']);
        $this->assertSame('app-store-or-testflight', $androidUpdateManifest['ios']['distribution']);
        $this->assertSame('https://raw.githubusercontent.com/jp2creation/hub_apple/main/releases/martin-sols-update.json', $androidUpdateManifest['ios']['manifestUrl']);
        $this->assertSame('https://raw.githubusercontent.com/jp2creation/hub_apple/main/releases/martin-sols-update.json', $androidUpdateManifest['macos']['manifestUrl']);
        $this->assertSame('https://raw.githubusercontent.com/jp2creation/hub_windows/main/martin-sols-update.json', $androidUpdateManifest['windows']['manifestUrl']);
        $this->assertStringContainsString("'repository_url' => 'https://github.com/jp2creation/hub_android'", $appDownloadsConfig);
        $this->assertStringContainsString("'manifest_url' => 'https://raw.githubusercontent.com/jp2creation/hub_apple/main/releases/martin-sols-update.json'", $appDownloadsConfig);
        $this->assertStringContainsString("env('HUB_ANDROID_STORE_URL', '')", $appDownloadsConfig);
        $this->assertFileDoesNotExist(base_path('.github/workflows/martin-sols-android-release.yml'));
        $this->assertStringContainsString('<color name="martin_sols_red">#95002E</color>', $androidColors);
        $this->assertStringContainsString('<color name="martin_sols_background">#F5F7FB</color>', $androidColors);
        $this->assertStringContainsString('parent="@android:style/Theme.Material.Light.NoActionBar"', $androidStyles);
        $this->assertStringNotContainsString('Theme.AppCompat', $androidStyles);
        $this->assertStringNotContainsString('Theme.SplashScreen', $androidStyles);
        $this->assertStringContainsString('<item name="android:windowNoTitle">true</item>', $androidStyles);
        $this->assertStringContainsString('<item name="android:windowActionBar">false</item>', $androidStyles);
        $this->assertStringNotContainsString('<item name="windowNoTitle">true</item>', $androidStyles);
        $this->assertStringNotContainsString('<item name="windowActionBar">false</item>', $androidStyles);
        $this->assertStringNotContainsString('postSplashScreenTheme', $androidStyles);
        $this->assertStringNotContainsString('<item name="android:background">@drawable/splash</item>', $androidStyles);
        $this->assertStringContainsString('<item name="android:statusBarColor">@color/martin_sols_red</item>', $androidStyles);
        $this->assertStringContainsString('<item name="android:windowTranslucentStatus">false</item>', $androidStyles);
        $this->assertStringContainsString('<item name="android:windowLightStatusBar">false</item>', $androidStyles);
        $this->assertStringContainsString('StatusBar.setStyle({ style: Style.Dark })', $mobileApp);
        $this->assertStringContainsString("StatusBar.setBackgroundColor({ color: '#95002e' })", $mobileApp);
        $this->assertStringNotContainsString('StatusBar.setOverlaysWebView', $mobileApp);
        $this->assertStringNotContainsString('startup-copy', $mobileApp);
        $this->assertStringContainsString('data-crm-mobile-check-update', $mobileSettings);
        $this->assertStringContainsString('crm-mobile-app-settings-content', $mobileSettings);
        $this->assertStringContainsString('crm-mobile-app-settings-group', $mobileSettings);
        $this->assertStringContainsString('crm-mobile-app-settings-group-title', $mobileSettings);
        $this->assertStringContainsString('crm-mobile-app-settings-row', $mobileSettings);
        $this->assertStringContainsString('Paramétrage de l’application', $mobileSettings);
        $this->assertStringContainsString('Plateforme', $mobileSettings);
        $this->assertStringContainsString('Tester la localisation', $mobileSettings);
        $this->assertStringContainsString('data-crm-mobile-clear-auth', $mobileSettings);
        $this->assertStringContainsString('data-crm-mobile-device-security', $mobileSettings);
        $this->assertStringContainsString('data-crm-mobile-auth-summary', $mobileSettings);
        $this->assertStringContainsString('data-crm-mobile-set-app-code', $mobileSettings);
        $this->assertStringContainsString('data-crm-mobile-set-app-code-label', $mobileSettings);
        $this->assertStringContainsString('data-crm-mobile-clear-app-code', $mobileSettings);
        $this->assertStringContainsString('Sécurité de l’appareil', $mobileSettings);
        $this->assertStringContainsString('Empreinte, visage ou code appareil', $mobileSettings);
        $this->assertStringContainsString('Ouverture des réglages iOS.', $mobileSettings);
        $this->assertStringContainsString('Ouverture des réglages de sécurité macOS.', $mobileSettings);
        $this->assertStringContainsString('Ouverture des réglages de sécurité Android.', $mobileSettings);
        $this->assertStringContainsString('Code app Martin Sols', $mobileSettings);
        $this->assertStringContainsString('Localisation terrain', $mobileSettings);
        $this->assertStringContainsString('Informations', $mobileSettings);
        $this->assertStringContainsString('Code app', $mobileSettings);
        $this->assertStringContainsString('platformLabel()', $mobileSettings);
        $this->assertStringContainsString('settingsIcon(', $mobileSettings);
        $this->assertStringContainsString('getMobileAuthStatus', $mobileSettings);
        $this->assertStringContainsString('/api/mobile/native-session', $mobileSettings);
        $this->assertStringContainsString('requestLocation?: (requestId: string, highAccuracy: boolean) => NativeBridgeResponse;', $mobileSettings);
        $this->assertStringContainsString('getPlatformName?: () => string;', $mobileSettings);
        $this->assertStringContainsString('martin-sols:native-location-result', $mobileSettings);
        $this->assertStringContainsString('clearMobileSession', $mobileSettings);
        $this->assertStringContainsString('setAppCode', $mobileSettings);
        $this->assertStringContainsString('clearAppCode', $mobileSettings);
        $this->assertStringContainsString('openDeviceSecuritySettings', $mobileSettings);
        $this->assertStringContainsString('window.MartinSolsNativeApp', $mobileSettings);
        $this->assertStringContainsString('Boolean(window.MartinSolsNativeApp)', $mobileSettings);
        $this->assertStringContainsString('checkForUpdates: requestUpdateCheck', $mobileSettings);
        $this->assertStringContainsString('data-native-login', $loginBlade);
        $this->assertStringContainsString('Connexion rapide', $loginBlade);
        $this->assertStringContainsString('/api/mobile/token', $loginBlade);
        $this->assertStringContainsString('/api/mobile/web-session', $loginBlade);
        $this->assertStringContainsString('/api/mobile/refresh', $loginBlade);
        $this->assertStringContainsString('authenticateSavedMobileSession', $loginBlade);
        $this->assertStringContainsString('saveMobileSession', $loginBlade);
        $this->assertStringContainsString('await saveNativeSession(session)', $loginBlade);
        $this->assertStringContainsString('async function nativeResult(value)', $loginBlade);
        $this->assertStringContainsString('nativeApp.getPlatformName?.()', $loginBlade);
        $this->assertStringContainsString('clearMobileSession', $loginBlade);
        $this->assertStringNotContainsString('crm-mobile-app-settings-trigger', $mobileSettings);
        $this->assertStringNotContainsString('crm-mobile-app-settings-backdrop', $mobileSettings);
        $this->assertStringNotContainsString('.startup-copy', $mobileStyles);
        $this->assertStringNotContainsString('auth-settings-button', $mobileStyles);
        $this->assertStringNotContainsString('crm-app-settings-button', $mobileStyles);
        $this->assertStringNotContainsString('startup-crm-loader', $mobileStyles);
        $this->assertStringContainsString('.startup-intro-media', $mobileStyles);
        $this->assertStringContainsString('position: absolute;', $mobileStyles);
        $this->assertStringContainsString('object-fit: cover;', $mobileStyles);
        $this->assertStringContainsString('html.crm-native-handoff #app', $mobileStyles);
        $this->assertStringContainsString('body.crm-mobile-app-settings-open', $shellCss);
        $this->assertStringContainsString('.crm-mobile-app-settings-content', $shellCss);
        $this->assertStringContainsString('.crm-mobile-app-settings-group', $shellCss);
        $this->assertStringContainsString('.crm-mobile-app-settings-group-title', $shellCss);
        $this->assertStringContainsString('.crm-mobile-app-settings-row-icon', $shellCss);
        $this->assertStringContainsString('.crm-mobile-app-settings-pill', $shellCss);
        $this->assertStringContainsString('.crm-mobile-app-settings-pill.is-warn', $shellCss);
        $this->assertStringContainsString('.crm-mobile-app-settings-mini-action', $shellCss);
        $this->assertStringContainsString('width: min(100%, 560px);', $shellCss);
        $this->assertStringContainsString('min-height: 100dvh;', $shellCss);
        $this->assertStringNotContainsString('.crm-mobile-app-settings-trigger', $shellCss);
        $this->assertStringNotContainsString('.crm-mobile-app-settings-backdrop', $shellCss);
        $this->assertStringNotContainsString('place-items: end center;', $shellCss);
        $this->assertStringNotContainsString('width: min(100%, 430px);', $shellCss);
        $this->assertStringNotContainsString('max-height: min(86dvh, 620px);', $shellCss);
        $this->assertStringContainsString('"overlaysWebView": false', $capacitorConfig);
        $this->assertStringContainsString('"style": "DARK"', $capacitorConfig);
        $this->assertStringContainsString('"backgroundColor": "#95002e"', $capacitorConfig);
        $this->assertStringNotContainsString('CapacitorHttp', $capacitorConfig);
        $this->assertStringNotContainsString('SplashScreen', $capacitorConfig);
        $this->assertStringContainsString('WKScriptMessageHandlerWithReply', $iosBridge);
        $this->assertStringContainsString('import LocalAuthentication', $iosBridge);
        $this->assertStringContainsString('import CoreLocation', $iosBridge);
        $this->assertStringContainsString('import Security', $iosBridge);
        $this->assertStringContainsString('private func saveMobileSessionPayload(_ payload: String) -> [String: Any]', $iosBridge);
        $this->assertStringContainsString('private func showSetAppCodeDialog(reply:', $iosBridge);
        $this->assertStringContainsString('private func showAppCodePrompt(requestId: String)', $iosBridge);
        $this->assertStringContainsString('private func requestNativeLocation(requestId: String, highAccuracy: Bool) -> [String: Any]', $iosBridge);
        $this->assertStringContainsString('private func dispatchNativeLocationResult(requestId: String, location: CLLocation?, error: String)', $iosBridge);
        $this->assertStringContainsString('getPlatformName() {', $iosBridge);
        $this->assertStringContainsString('NSFaceIDUsageDescription', $iosInfoPlist);
        $this->assertStringContainsString('WKScriptMessageHandlerWithReply', $macApp);
        $this->assertStringContainsString('import LocalAuthentication', $macApp);
        $this->assertStringContainsString('import CoreLocation', $macApp);
        $this->assertStringContainsString('import Security', $macApp);
        $this->assertStringContainsString('private func saveMobileSessionPayload(_ payload: String) -> [String: Any]', $macApp);
        $this->assertStringContainsString('private func showSetAppCodeDialog() -> [String: Any]', $macApp);
        $this->assertStringContainsString('private func showAppCodePrompt(requestId: String)', $macApp);
        $this->assertStringContainsString('private func requestNativeLocation(requestId: String, highAccuracy: Bool) -> [String: Any]', $macApp);
        $this->assertStringContainsString('private func dispatchNativeLocationResult(requestId: String, location: CLLocation?, error: String)', $macApp);
        $this->assertStringContainsString('document.documentElement.classList.add(\'crm-mac-app\')', $macApp);
        $this->assertStringContainsString('getPlatformName() {', $macApp);
        $this->assertStringContainsString('NSLocationUsageDescription', $macInfoPlist);
        $this->assertStringContainsString('@import "./template-compat/variables.css"', $templateCompatCss);
        $this->assertStringContainsString('@import "./template-compat/components.css"', $templateCompatCss);
        $this->assertStringContainsString('--theme-primary: 149 0 46;', $templateVariablesCss);
        $this->assertStringContainsString('--theme-accent: 245 178 18;', $templateVariablesCss);
        $this->assertStringContainsString('--color-secondary-900: #1d354f;', $templateVariablesCss);
        $this->assertStringContainsString('--shadow-card:', $templateVariablesCss);
        $this->assertStringContainsString('.card', $templateComponentsCss);
        $this->assertStringContainsString('.btn-primary', $templateComponentsCss);
        $this->assertStringContainsString('window.MartinSolsUi', $nativeUi);
        $this->assertStringContainsString('renderSegmentControl', $nativeUi);
        $this->assertStringContainsString('renderProductGrid', $nativeUi);
        $this->assertStringContainsString('bindNavigation', $nativeUi);
        $this->assertStringContainsString('setTemplateDefaults', $nativeUi);
        $this->assertStringContainsString('crm-ui-route-transitioning', $nativeUi);
        $this->assertStringContainsString("html.dataset.cardStyle = html.dataset.cardStyle || 'shadow'", $nativeUi);
        $this->assertStringContainsString('--crm-header-height: 64px;', $shellCss);
        $this->assertStringContainsString('margin-left: auto;', $shellCss);
        $this->assertStringContainsString('html.crm-ui-route-transitioning .crm-native-content', $shellCss);
        $this->assertStringContainsString('crm-template-fade-in', $shellCss);
        $this->assertStringContainsString('body.ms-ui-modal-open', $nativeUiCss);
        $this->assertStringContainsString('--ms-ui-shadow-card', $nativeUiCss);
        $this->assertStringContainsString('.dash-card', $nativeUiCss);
        $this->assertStringContainsString('.ms-ui-product-card', $nativeUiCss);
        $this->assertStringContainsString('.resa-product-card', $nativeUiCss);
        $this->assertStringContainsString('.rent-product-card', $nativeUiCss);
        $this->assertStringContainsString('.crm-native-content .rent-product-card .rent-product-image img', $nativeUiCss);
        $this->assertStringContainsString('aspect-ratio: 1 / 1 !important;', $nativeUiCss);
        $this->assertStringContainsString('border-bottom: 1px solid rgb(226 232 240) !important;', $nativeUiCss);
        $this->assertStringContainsString('padding: 0.88rem !important;', $nativeUiCss);
        $this->assertStringContainsString('min-height: 13.8rem !important;', $nativeUiCss);
        $this->assertStringContainsString('padding: 0.58rem !important;', $nativeUiCss);
        $this->assertStringNotContainsString('has-no-visible-price', $nativeUiCss);
        $this->assertStringContainsString('.ms-ui-segment', $nativeUiCss);
        $this->assertStringContainsString('.resa-dialog', $nativeUiCss);
        $this->assertStringContainsString('.rent-dialog', $nativeUiCss);
        $this->assertStringContainsString('Unified HUB module dialogs', $nativeUiCss);
        $this->assertStringContainsString('.check-modal-backdrop', $nativeUiCss);
        $this->assertStringContainsString('.deposit-modal-backdrop', $nativeUiCss);
        $this->assertStringContainsString('.leaves-modal-backdrop', $nativeUiCss);
        $this->assertStringContainsString('.cash-modal-backdrop', $nativeUiCss);
        $this->assertStringContainsString('.doc-modal-backdrop', $nativeUiCss);
        $this->assertStringContainsString('.crm-modal-backdrop', $nativeUiCss);
        $this->assertStringContainsString('.tour-modal-backdrop', $nativeUiCss);
        $this->assertStringContainsString('.sales-modal-backdrop', $nativeUiCss);
        $this->assertStringContainsString('content: "\\2190  Retour";', $nativeUiCss);
        $this->assertStringContainsString('bottom: calc(0.65rem + env(safe-area-inset-bottom)) !important;', $nativeUiCss);
        $this->assertStringContainsString('width: min(35rem, calc(100vw - 1rem)) !important;', $nativeUiCss);
        $this->assertStringContainsString('.crm-modal-actions', $nativeUiCss);
    }

    public function test_static_assets_keep_only_brand_and_pwa_files(): void
    {
        $assetsDir = resource_path('frontend/static/assets');

        $this->assertFileExists($assetsDir.'/logo/martin-sols-logo.png');
        $this->assertFileExists($assetsDir.'/logo/logomark.png');
        $this->assertFileExists($assetsDir.'/pwa/icon-192.png');
        $this->assertFileExists($assetsDir.'/pwa/icon-512.png');
        $this->assertFileDoesNotExist($assetsDir.'/logo/logo.svg');
        $this->assertFileDoesNotExist($assetsDir.'/logo/logo-dark.svg');
        $this->assertSame([], glob($assetsDir.'/*.js') ?: []);
        $this->assertSame([], glob($assetsDir.'/*.css') ?: []);
        $this->assertDirectoryDoesNotExist($assetsDir.'/products');
        $this->assertDirectoryDoesNotExist($assetsDir.'/gallery');
        $this->assertDirectoryDoesNotExist($assetsDir.'/avatars');

        $androidIconDir = base_path('mobile/android/app/src/main/res/mipmap-xxxhdpi');
        $this->assertFileExists($androidIconDir.'/ic_launcher.png');
        $this->assertFileExists($androidIconDir.'/ic_launcher_round.png');
        $this->assertFileExists($androidIconDir.'/ic_launcher_foreground.png');
        $this->assertSame([192, 192], array_slice(getimagesize($androidIconDir.'/ic_launcher.png') ?: [], 0, 2));
        $this->assertSame([432, 432], array_slice(getimagesize($androidIconDir.'/ic_launcher_foreground.png') ?: [], 0, 2));
        $this->assertSame('4a6c9c82f0c23541c06922add7ae96b41f6e01bc849a44c54ebddc7b5369dbd1', hash_file('sha256', $androidIconDir.'/ic_launcher.png'));
        $this->assertSame('7e7a85e18e6f16800e42e4e5c89bb58708a2c86f3d49ee832a4ae33b63e1abb7', hash_file('sha256', $androidIconDir.'/ic_launcher_foreground.png'));
    }

    public function test_conges_cards_use_global_background_theme(): void
    {
        $asset = (string) file_get_contents(base_path('Modules/CrmLeaves/resources/assets/crm-conges.js'));

        $this->assertStringContainsString('--leave-panel:#fff;', $asset);
        $this->assertStringContainsString('--leave-panel-soft:var(--color-secondary-50,#fafafa);', $asset);
        $this->assertStringContainsString('--leave-card-border:var(--color-surface-200,#e4e4e7);', $asset);
        $this->assertStringContainsString('--leave-card-radius:var(--radius,.625rem);', $asset);
        $this->assertStringContainsString('--leave-card-shadow:var(--shadow-card,0 1px 2px rgb(0 0 0 / 0.04),0 8px 24px -4px rgb(0 0 0 / 0.06));', $asset);
        $this->assertStringContainsString('background:var(--color-secondary-50,#fafafa);', $asset);
        $this->assertStringContainsString('background:var(--leave-panel);', $asset);
        $this->assertStringContainsString('background:var(--leave-panel-soft);', $asset);
        $this->assertStringContainsString('border:1px solid var(--leave-card-border);', $asset);
        $this->assertStringContainsString('border-radius:var(--leave-card-radius);', $asset);
        $this->assertStringContainsString('box-shadow:var(--leave-card-shadow);', $asset);
        $this->assertStringContainsString('<div class="leave-header-top">', $asset);
        $this->assertStringContainsString('.layout-container.layout-page:has(#crm-leaves-module),', $asset);
        $this->assertStringContainsString('.layout-page:has(#crm-leaves-module){width:100%;max-width:100%;min-width:0;overflow-x:hidden}', $asset);
        $this->assertStringContainsString('main:has(#crm-leaves-module){min-width:0;overflow-x:hidden}', $asset);
        $this->assertStringContainsString('<em>${esc(card.detail)}</em>', $asset);
        $this->assertStringContainsString('<p class="leave-header-subtitle">${esc(activeSiteName())}</p>', $asset);
        $this->assertStringContainsString('#crm-leaves-module .leave-header-subtitle', $asset);
        $this->assertStringContainsString('grid-template-columns:minmax(0,1fr);', $asset);
        $this->assertStringContainsString('grid-column:1/-1;', $asset);
        $this->assertStringContainsString('inline-size:100%;', $asset);
        $this->assertStringContainsString('max-inline-size:none;', $asset);
        $this->assertStringContainsString('grid-template-columns:repeat(4,minmax(0,1fr));', $asset);
        $this->assertStringContainsString('justify-items:stretch;', $asset);
        $this->assertStringContainsString('justify-self:stretch;', $asset);
        $this->assertStringContainsString('background:transparent;', $asset);
        $this->assertStringContainsString('box-shadow:none;', $asset);
        $this->assertStringContainsString('grid-template-columns:2.6rem minmax(0,1fr);', $asset);
        $this->assertStringContainsString('box-shadow:0 12px 28px rgba(15,23,42,.05);', $asset);
        $this->assertStringContainsString('min-height:2.35rem;', $asset);
        $this->assertStringContainsString('border-radius:.5rem;', $asset);
        $this->assertStringContainsString('box-shadow:0 10px 24px rgba(15,23,42,.04);', $asset);
        $this->assertStringContainsString('content:none;', $asset);
        $this->assertStringContainsString('font-size:1.45rem;', $asset);

        $headerStart = strpos($asset, 'function renderHeader()');
        $headerEnd = strpos($asset, 'function icon(name)', $headerStart ?: 0);
        $calendarStart = strpos($asset, 'function renderCalendar()');
        $calendarEnd = strpos($asset, 'function renderWorkflowPanel()', $calendarStart ?: 0);
        $balancesStart = strpos($asset, 'function renderBalancesPanel()');
        $balancesEnd = strpos($asset, 'function renderRequestsTable()', $balancesStart ?: 0);
        $balancePanelStart = strpos($asset, 'function renderBalancePanel()');
        $balancePanelEnd = strpos($asset, 'async function request(', $balancePanelStart ?: 0);

        if (
            $headerStart === false ||
            $headerEnd === false ||
            $calendarStart === false ||
            $calendarEnd === false ||
            $balancesStart === false ||
            $balancesEnd === false ||
            $balancePanelStart === false ||
            $balancePanelEnd === false
        ) {
            $this->fail('Le module Congés ne contient plus les fonctions de rendu attendues.');
        }

        $headerSource = substr($asset, $headerStart, $headerEnd - $headerStart);
        $calendarSource = substr($asset, $calendarStart, $calendarEnd - $calendarStart);
        $balancesSource = substr($asset, $balancesStart, $balancesEnd - $balancesStart);
        $balancePanelSource = substr($asset, $balancePanelStart, $balancePanelEnd - $balancePanelStart);

        $this->assertStringContainsString('${renderTopMetrics()}', $headerSource);
        $this->assertStringContainsString('leave-header-subtitle', $headerSource);
        $this->assertStringNotContainsString('leave-header-icons', $headerSource);
        $this->assertStringNotContainsString('leave-round-icon', $headerSource);
        $this->assertStringNotContainsString('data-filter-focus', $asset);
        $this->assertStringNotContainsString('${renderTopMetrics()}', $calendarSource);
        $this->assertStringNotContainsString('${renderTopMetrics()}', $balancesSource);
        $this->assertStringNotContainsString('leave-profile-card', $balancePanelSource);
        $this->assertStringNotContainsString('leave-balance-grid', $balancePanelSource);
        $this->assertStringContainsString('leave-type-card leave-sidebar-card', $balancePanelSource);
        $this->assertStringContainsString('Absences par type', $balancePanelSource);
        $this->assertStringContainsString("views.push({ key: 'settings', label: 'Gestion' });", $asset);
        $this->assertStringContainsString('data-add-type', $asset);
        $this->assertStringContainsString('data-edit-type', $asset);
        $this->assertStringContainsString('data-toggle-type', $asset);
        $this->assertStringContainsString('data-delete-type', $asset);
        $this->assertStringContainsString('data-type-form', $asset);
        $this->assertStringContainsString('${renderTypeModal()}', $asset);
        $this->assertStringContainsString("request('save_type'", $asset);
        $this->assertStringContainsString("request('toggle_type_visibility'", $asset);
        $this->assertStringContainsString("request('delete_type'", $asset);
        $this->assertStringContainsString('selectableLeaveTypes(form.type)', $asset);
        $this->assertStringContainsString('leave-type-state', $asset);
        $this->assertStringContainsString('.leaves-type-modal', $asset);

        foreach ([
            '#fffdfa',
            '#fbfaf7',
            '#f4f2ee',
            '#f8f7f4',
            '#fbfaf6',
            '#f3f6fb',
            '#ddd9cf',
            '#dedbd3',
            '#f6edf1',
            '#f8e9ef',
            '#f0efeb',
        ] as $legacyBackground) {
            $this->assertStringNotContainsString($legacyBackground, $asset);
        }
    }

    public function test_deployment_archive_includes_vite_build_output(): void
    {
        $script = (string) file_get_contents(base_path('scripts/deploy-planethoster.sh'));
        $gitignore = (string) file_get_contents(base_path('.gitignore'));

        $this->assertStringContainsString('tar -rf "$LOCAL_ARCHIVE_TAR" public/build', $script);
        $this->assertStringContainsString('if [ -d public/build ]; then', $script);
        $this->assertStringNotContainsString('if [ "$CRM_DEPLOY_BUILD" != "0" ] && [ -d public/build ]; then', $script);
        $this->assertStringContainsString('Manifest Vite absent: ${RELEASE_DIR}/public/build/manifest.json', $script);
        $this->assertStringContainsString('php artisan hub:publish-static-assets --force --clean', $script);
        $this->assertStringContainsString('php artisan hub:publish-module-assets --force', $script);
        $this->assertStringContainsString('gzip -c "$LOCAL_ARCHIVE_TAR" > "$LOCAL_ARCHIVE"', $script);
        $this->assertStringContainsString('RELEASES_DIR="${CRM_DEPLOY_ROOT}/releases"', $script);
        $this->assertStringContainsString('SHARED_DIR="${CRM_DEPLOY_ROOT}/shared"', $script);
        $this->assertStringContainsString('CURRENT_LINK="${CRM_DEPLOY_ROOT}/current"', $script);
        $this->assertStringContainsString('mv -Tf "$NEXT_LINK" "$CURRENT_LINK"', $script);
        $this->assertStringContainsString('rollback_current', $script);
        $this->assertStringContainsString('curl -fsS --max-time 10 "$health_url"', $script);
        $this->assertStringContainsString('php artisan horizon:terminate || true', $script);
        $this->assertStringContainsString('cleanup_old_releases', $script);
        $this->assertStringContainsString("--exclude='storage/redis'", $script);
        $this->assertStringContainsString("--exclude='storage/framework/cache'", $script);
        $this->assertStringContainsString('/public/assets', $gitignore);
        $this->assertStringContainsString('/public/modules', $gitignore);
    }

    public function test_hub_administration_uses_integrated_ergonomic_shell(): void
    {
        $administration = (string) file_get_contents(base_path('Modules/CrmAdministration/resources/assets/crm-administration.js'));

        $this->assertFileExists(base_path('Modules/CrmAdministration/resources/assets/logo-hub.svg'));
        $this->assertFileDoesNotExist(base_path('Modules/CrmAdministration/resources/assets/logo-hub.png'));
        $this->assertStringContainsString('import hubLogoUrl from "./logo-hub.svg";', $administration);
        $this->assertStringContainsString('class="admin-title-logo"', $administration);
        $this->assertStringContainsString('alt="HUB"', $administration);
        $this->assertStringNotContainsString('Administration HUB', $administration);
        $this->assertStringContainsString('font-size:1.8rem;line-height:1.1;font-weight:600', $administration);
        $this->assertStringContainsString('["overview", "Vue d\'ensemble", "Pilotage", "dashboard"]', $administration);
        $this->assertStringContainsString('class="admin-workspace"', $administration);
        $this->assertStringNotContainsString('class="admin-sidebar"', $administration);
        $this->assertStringNotContainsString('class="admin-nav-card"', $administration);
        $this->assertStringNotContainsString('class="admin-tabs"', $administration);
        $this->assertStringContainsString('class="admin-stats"', $administration);
        $this->assertStringContainsString('function renderOverview()', $administration);
        $this->assertStringContainsString('function renderListRow', $administration);
        $this->assertStringContainsString('admin-list-card', $administration);
        $this->assertStringContainsString('color-mix(in srgb,var(--admin-pill-color', $administration);
        $this->assertStringContainsString('function renderModal()', $administration);
        $this->assertStringContainsString('adminDrawerIn', $administration);
        $this->assertStringContainsString('admin-modal-back-button', $administration);
        $this->assertStringContainsString('admin-modal-close-button', $administration);
        $this->assertStringContainsString('width:min(35rem,66.666vw)', $administration);
        $this->assertStringContainsString('66.666vw', $administration);
        $this->assertStringContainsString('@media (max-width:1024px)', $administration);
        $this->assertStringContainsString('Retour</span>', $administration);
        $this->assertStringContainsString('data-edit-type="user-roles"', $administration);
        $this->assertStringContainsString('data-user-roles-form', $administration);
        $this->assertStringContainsString('admin-site-form', $administration);
        $this->assertStringContainsString('admin-form-section', $administration);
        $this->assertStringContainsString('Identité du site', $administration);
        $this->assertStringContainsString('admin-site-identity-grid', $administration);
        $this->assertStringContainsString('admin-site-color-field input{width:2.45rem;height:2.45rem', $administration);
        $this->assertStringContainsString('Coordonnées', $administration);
        $this->assertStringContainsString('Horaires du site', $administration);
        $this->assertStringContainsString('Photo en arrière-plan', $administration);
        $this->assertStringContainsString('name="showPhotoInHeader"', $administration);
        $this->assertStringContainsString('showPhotoInHeader: Boolean(data.get("showPhotoInHeader"))', $administration);
        $this->assertStringContainsString('fond masqué', $administration);
        $this->assertStringContainsString('admin-site-hours-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr))', $administration);
        $this->assertStringContainsString('admin-site-hours-grid,#${rootId} .admin-asset-prices-grid{grid-template-columns:repeat(2,minmax(0,1fr))', $administration);
        $this->assertStringContainsString('admin-site-form-footer', $administration);
        $this->assertStringContainsString('data-delete-menu-item', $administration);
        $this->assertStringContainsString('function deleteMenuItem', $administration);
        $this->assertStringContainsString('delete_menu_item', $administration);
        $this->assertStringContainsString('Supprimer ce lien du menu', $administration);
        $this->assertStringContainsString('admin-modal-body > form{box-sizing:border-box;min-height:100%}', $administration);
        $this->assertStringContainsString('admin-actions,#${rootId} .admin-site-form-footer,#${rootId} .admin-role-actions{position:fixed;right:auto;bottom:calc(.65rem + env(safe-area-inset-bottom));left:50%', $administration);
        $this->assertStringContainsString('width:max-content;max-width:calc(100vw - 2rem);transform:translateX(-50%)', $administration);
        $this->assertStringContainsString('min-width:5.45rem;max-width:8.75rem', $administration);
        $this->assertStringContainsString('admin-role-wizard', $administration);
        $this->assertStringContainsString('admin-modal-role', $administration);
        $this->assertStringContainsString('Profil et accès rapides', $administration);
        $this->assertStringContainsString('Profil de départ', $administration);
        $this->assertStringContainsString('Niveau de droits rapide', $administration);
        $this->assertStringContainsString('Permissions rapides', $administration);
        $this->assertStringContainsString('Choisir vite les accès', $administration);
        $this->assertStringContainsString('Sites autorisés', $administration);
        $this->assertStringContainsString('Ajustements avancés', $administration);
        $this->assertStringContainsString('Modules activés automatiquement', $administration);
        $this->assertStringContainsString('admin-role-primary-grid', $administration);
        $this->assertStringContainsString('admin-role-flow', $administration);
        $this->assertStringContainsString('admin-role-panel-head', $administration);
        $this->assertStringContainsString('admin-role-advanced-layout', $administration);
        $this->assertStringContainsString('Récapitulatif du rôle', $administration);
        $this->assertStringContainsString('data-module-access-level', $administration);
        $this->assertStringContainsString('data-role-preset', $administration);
        $this->assertStringContainsString('function applyRolePreset', $administration);
        $this->assertStringContainsString('function setModuleAccessLevel', $administration);
        $this->assertStringContainsString('data-apply-role-profile', $administration);
        $this->assertStringContainsString('data-user-filter-reset', $administration);
        $this->assertStringContainsString('data-user-filter="siteId"', $administration);
        $this->assertStringContainsString('data-user-filter="role"', $administration);
        $this->assertStringContainsString('function filterUsers', $administration);
        $this->assertStringContainsString('data-edit-type', $administration);
        $this->assertStringContainsString('admin-modal-wide', $administration);
        $this->assertStringContainsString('data-menu-group-form', $administration);
        $this->assertStringContainsString('data-menu-item-form', $administration);
        $this->assertStringContainsString('data-menu-drag-row', $administration);
        $this->assertStringContainsString('data-menu-drag-list', $administration);
        $this->assertStringContainsString('admin-menu-tree', $administration);
        $this->assertStringContainsString('admin-menu-tree-row-group', $administration);
        $this->assertStringContainsString('admin-menu-tree-row-item', $administration);
        $this->assertStringContainsString('admin-menu-tree-row-subitem', $administration);
        $this->assertStringContainsString('data-menu-parent-group', $administration);
        $this->assertStringContainsString('data-menu-parent-item', $administration);
        $this->assertStringContainsString('parentItemKey', $administration);
        $this->assertStringContainsString('Page parente', $administration);
        $this->assertStringContainsString('function reorderMenu', $administration);
        $this->assertStringContainsString('function reorderMenuGroup', $administration);
        $this->assertStringContainsString('function reorderMenuItem', $administration);
        $this->assertStringContainsString('function reorderSites', $administration);
        $this->assertStringContainsString('function saveMenuOrder', $administration);
        $this->assertStringContainsString('request("reorder_sites"', $administration);
        $this->assertStringContainsString('Glissez les sites pour choisir leur ordre', $administration);
        $this->assertStringContainsString('crm:navigation-refresh', $administration);
        $this->assertStringContainsString('is-drop-before', $administration);
        $this->assertStringContainsString('data-admin-search', $administration);
        $this->assertStringContainsString('url.pathname = next === "overview" ? "/administration" : `/administration/${next}`;', $administration);
    }

    public function test_site_contact_and_color_are_exposed_in_frontend_modules(): void
    {
        $teams = (string) file_get_contents(base_path('Modules/CrmTeams/resources/assets/crm-equipes.js'));
        $administration = (string) file_get_contents(base_path('Modules/CrmAdministration/resources/assets/crm-administration.js'));
        $activeSite = (string) file_get_contents(base_path('Modules/CrmCore/resources/assets/crm-active-site.js'));

        $this->assertStringContainsString('function renderSiteInfo(site)', $teams);
        $this->assertStringContainsString('Informations du site sélectionné', $teams);
        $this->assertStringContainsString('${siteInfoItem("Adresse", site?.address || "", "mapPin")}', $teams);
        $this->assertStringContainsString('${siteInfoItem("Téléphone", site?.phone || "", "phone", site?.phone ? `tel:${phoneHref(site.phone)}` : "")}', $teams);
        $this->assertStringContainsString('const photoUrl = sitePhotoUrl(site);', $teams);
        $this->assertStringContainsString('if (site?.showPhotoInHeader === false) return "";', $teams);
        $this->assertStringContainsString('class="teams-site-info${photoUrl ? " has-site-photo" : ""}"', $teams);
        $this->assertStringContainsString('style="${siteStyle(color, photoUrl)}"', $teams);
        $this->assertStringContainsString('--site-photo:url', $teams);
        $this->assertStringContainsString('.teams-site-info.has-site-photo::before', $teams);
        $this->assertStringContainsString('mask-image:linear-gradient(90deg,#000 0%,#000 54%,transparent 100%)', $teams);
        $this->assertStringContainsString('window.addEventListener(activeSiteEvent', $teams);
        $this->assertStringContainsString('data-teams-contact-list', $teams);
        $this->assertStringContainsString('<th>Contact</th>', $teams);
        $this->assertStringContainsString('<th>Téléphone</th>', $teams);
        $this->assertStringContainsString('<th>Rôle</th>', $teams);
        $this->assertStringContainsString('<th>Actions</th>', $teams);
        $this->assertStringContainsString('class="teams-contact-link"', $teams);
        $this->assertStringContainsString('class="teams-actions"', $teams);
        $this->assertStringContainsString('function renderMemberActions(member)', $teams);
        $this->assertStringContainsString('admin: "Administrateur"', $teams);
        $this->assertStringContainsString('.teams-table{width:100%;min-width:50rem;border-collapse:separate;border-spacing:0}', $teams);
        $this->assertStringContainsString('.teams-table td{border-top:1px solid var(--teams-border);padding:.68rem 1rem', $teams);
        $this->assertStringContainsString('.teams-member{display:grid;grid-template-columns:1.8rem minmax(0,1fr)', $teams);
        $this->assertStringContainsString('.teams-avatar{position:relative;display:grid;place-items:center;width:1.8rem;height:1.8rem', $teams);
        $this->assertStringNotContainsString('<th>Prénom</th>', $teams);
        $this->assertStringNotContainsString('<th>Nom</th>', $teams);
        $this->assertStringNotContainsString('class="teams-sites"', $teams);
        $this->assertStringNotContainsString('data-site-id', $teams);
        $this->assertStringNotContainsString('function renderSiteButton', $teams);

        $this->assertStringContainsString('<label class="admin-site-color-field">Couleur <input name="color" type="color"', $administration);
        $this->assertStringContainsString('<label>Téléphone <input name="phone" type="tel"', $administration);
        $this->assertStringContainsString('<label>Adresse <input name="address"', $administration);
        $this->assertStringContainsString('function renderSitePhoto(site)', $administration);
        $this->assertStringContainsString('data-site-photo-input', $administration);
        $this->assertStringContainsString('name="photoDataUrl"', $administration);
        $this->assertStringContainsString('photoDataUrl: String(data.get("photoDataUrl") || "")', $administration);
        $this->assertStringContainsString('function readFileAsDataUrl(file)', $administration);
        $this->assertStringContainsString('window.CRM_ACTIVE_SITE?.reload?.();', $administration);

        $this->assertStringContainsString('function martinSiteMark(className)', $activeSite);
        $this->assertStringContainsString('.crm-active-site-control{position:relative;min-width:0;flex:1 1 auto;width:100%}', $activeSite);
        $this->assertStringContainsString('button.style.setProperty(\'--active-site-color\', selectedColor);', $activeSite);
        $this->assertStringContainsString('clamp(10rem,44vw,12rem)', $activeSite);
        $this->assertStringContainsString('crm-active-site-option-mark', $activeSite);
        $this->assertStringContainsString('color-mix(in srgb,var(--site-mark-primary) 50%,#fff)', $activeSite);
        $this->assertStringContainsString("'.crm-active-site-option.is-active{background:rgb(var(--theme-primary) / .11);color:rgb(var(--theme-primary))}'", $activeSite);
        $this->assertStringNotContainsString('crm-active-site-option-dot', $activeSite);
        $this->assertStringNotContainsString('crm-active-site-option-icon', $activeSite);
        $this->assertStringNotContainsString('crm-active-site-dot', $activeSite);
        $this->assertStringNotContainsString('.crm-active-site-trigger.has-site-color', $activeSite);
        $this->assertStringNotContainsString('function contrastColor(color)', $activeSite);
    }

    public function test_reservation_vehicle_selector_uses_compact_hub_cards(): void
    {
        $reservations = (string) file_get_contents(base_path('Modules/CrmReservations/resources/assets/crm-reservations.js'));
        $nativeUiCss = (string) file_get_contents(resource_path('frontend/crm/styles/native-ui.css'));

        $this->assertStringContainsString('resa-card resa-vehicle-card', $reservations);
        $this->assertStringContainsString('resa-card-count', $reservations);
        $this->assertStringContainsString('repeat(auto-fill,minmax(min(100%,18rem),18rem))', $reservations);
        $this->assertStringContainsString('grid-template-columns:5.45rem minmax(0,1fr)', $reservations);
        $this->assertStringContainsString('.resa-vehicle-card .resa-card-body{background:#fafafa}', $reservations);
        $this->assertStringContainsString('resa-product-status', $reservations);
        $this->assertStringContainsString('#${rootId} .resa-vehicles{grid-template-columns:1fr;gap:.65rem}', $reservations);
        $this->assertStringContainsString('.resa-vehicles {', $nativeUiCss);
        $this->assertStringContainsString('.resa-vehicle-card .resa-product-image {', $nativeUiCss);
        $this->assertStringContainsString('object-fit: cover !important;', $nativeUiCss);
        $this->assertStringContainsString('grid-template-columns: 1fr !important;', $nativeUiCss);
        $this->assertStringContainsString('.resa-product-card {', $nativeUiCss);
        $this->assertStringNotContainsString('class="resa-dot', $reservations);
    }

    public function test_dashboard_top_cards_use_two_columns_on_mobile(): void
    {
        $dashboard = (string) file_get_contents(base_path('Modules/CrmCore/resources/assets/crm-dashboard.js'));

        $this->assertFileExists(base_path('Modules/CrmAdministration/resources/assets/logo-hub.svg'));
        $this->assertStringContainsString('import hubLogoUrl from "../../../CrmAdministration/resources/assets/logo-hub.svg";', $dashboard);
        $this->assertStringContainsString('Tableau de bord</span><img class="dash-title-logo"', $dashboard);
        $this->assertStringNotContainsString('Tableau de bord du', $dashboard);
        $this->assertStringContainsString('class="dash-title-logo"', $dashboard);
        $this->assertStringContainsString('alt="HUB"', $dashboard);
        $this->assertStringContainsString('@media (max-width:720px)', $dashboard);
        $this->assertStringContainsString('.dash-title-logo{height:1.38rem;max-width:4.2rem}', $dashboard);
        $this->assertStringContainsString('.dash-stats{grid-template-columns:repeat(2,minmax(0,1fr));gap:.65rem}', $dashboard);
        $this->assertStringContainsString('.dash-stat{grid-template-columns:2.2rem minmax(0,1fr);gap:.55rem;padding:.72rem}', $dashboard);
        $this->assertStringContainsString('.dash-stats .dash-empty{grid-column:1/-1}', $dashboard);
    }

    public function test_dashboard_integrates_quick_access_module_cards(): void
    {
        $dashboard = (string) file_get_contents(base_path('Modules/CrmCore/resources/assets/crm-dashboard.js'));

        $this->assertStringContainsString('${renderQuickAccess(data)}', $dashboard);
        $this->assertStringContainsString('function renderQuickAccess(data)', $dashboard);
        $this->assertStringContainsString('Accès rapide', $dashboard);
        $this->assertStringContainsString('dash-card dash-quick', $dashboard);
        $this->assertStringContainsString('dash-quick-grid', $dashboard);
        $this->assertStringContainsString('dash-quick-card', $dashboard);
        $this->assertStringContainsString('Personnaliser', $dashboard);
        $this->assertStringContainsString('aria-label="Personnaliser les accès rapides"', $dashboard);
        $this->assertStringContainsString('<span>Personnaliser</span>', $dashboard);
        $this->assertStringContainsString('data-quick-customize', $dashboard);
        $this->assertStringContainsString('${renderQuickAccessModal(data)}', $dashboard);
        $this->assertStringContainsString('function renderQuickAccessModal(data)', $dashboard);
        $this->assertStringContainsString('dash-modal-backdrop', $dashboard);
        $this->assertStringContainsString('dash-modal-back-button', $dashboard);
        $this->assertStringContainsString('dash-quick-settings-list', $dashboard);
        $this->assertStringContainsString('data-quick-enabled', $dashboard);
        $this->assertStringContainsString('data-quick-drag-row', $dashboard);
        $this->assertStringContainsString('function moveQuickAccessDraft(fromSlug, toSlug)', $dashboard);
        $this->assertStringContainsString('function saveQuickAccess()', $dashboard);
        $this->assertStringContainsString('save_quick_access', $dashboard);
        $this->assertStringContainsString('module.slug !== "dashboard"', $dashboard);
        $this->assertStringContainsString('function moduleQuickMeta(module)', $dashboard);
        $this->assertStringContainsString('Réservations véhicules', $dashboard);
        $this->assertStringContainsString('Location matériel', $dashboard);
        $this->assertStringNotContainsString('<div class="dash-actions">', $dashboard);
        $this->assertStringNotContainsString('href="/locations-materiel">${icon("plus")}Location matériel', $dashboard);
        $this->assertStringNotContainsString('href="/controle-caisse">${icon("receipt")}Contrôle caisse', $dashboard);
        $this->assertStringContainsString('target="_blank" rel="noopener noreferrer"', $dashboard);
        $this->assertStringContainsString('.dash-quick-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.85rem}', $dashboard);
        $this->assertStringContainsString('.dash-stats,#${rootId} .dash-quick-grid{grid-template-columns:repeat(2,minmax(0,1fr))}', $dashboard);
        $this->assertStringContainsString('.dash-quick-header{align-items:flex-start;flex-direction:row}', $dashboard);
        $this->assertStringContainsString('.dash-quick-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:.65rem}', $dashboard);
        $this->assertStringContainsString('.dash-quick-card{grid-template-columns:minmax(0,1fr);min-height:7.25rem;gap:.55rem;padding:.72rem}', $dashboard);
        $this->assertStringContainsString('.dash-quick-arrow{display:none}', $dashboard);
        $this->assertStringContainsString('.dash-quick-customize{flex:0 0 2.35rem;width:2.35rem;min-width:2.35rem;height:2.35rem;min-height:2.35rem;padding:0;gap:0}', $dashboard);
        $this->assertStringContainsString('.dash-quick-customize span{display:none}', $dashboard);
        $this->assertStringContainsString('@media (max-width:1024px)', $dashboard);
    }

    public function test_dom_ready_sensitive_crm_modules_boot_even_when_loaded_late(): void
    {
        foreach ([
            base_path('Modules/CrmAdministration/resources/assets/crm-administration.js'),
            base_path('Modules/CrmCashControl/resources/assets/crm-controle-caisse.js'),
            base_path('Modules/CrmCore/resources/assets/crm-account-settings.js'),
            base_path('Modules/CrmCore/resources/assets/crm-active-site.js'),
            base_path('Modules/CrmCore/resources/assets/crm-dashboard.js'),
            base_path('Modules/CrmCore/resources/assets/crm-text-fixes.js'),
            base_path('Modules/CrmEquipmentRentals/resources/assets/crm-equipment-rentals.js'),
            base_path('Modules/CrmReservations/resources/assets/crm-reservations.js'),
            base_path('Modules/CrmTapisRomus/resources/assets/crm-tapis-romus.js'),
        ] as $assetPath) {
            $asset = (string) file_get_contents($assetPath);

            $this->assertStringContainsString('document.readyState ===', $asset, $assetPath);
        }
    }
}
